In [1]:
import pandas as pd

In [3]:
df = pd.read_pickle('final_dataset.pkl')

In [25]:
df.head(-1)

,event_time,product_id,category_id,category_code,brand,price,user_id,day,week,month,year,cart,purchase,view
0,2019-10-21 16:17:11+00:00,1801805,2053013554415534427,electronics.video.tv,artel,231.60,536042235,0,43,10,1,0,0,1
1,2019-10-21 14:42:20+00:00,1004870,2053013555631882655,electronics.smartphone,samsung,284.02,517143806,0,43,10,1,1,0,0
2,2019-10-03 18:40:22+00:00,5701087,2053013553970938175,auto.accessories.player,jvc,51.48,556492770,3,40,10,1,0,0,1
3,2019-10-18 15:55:13+00:00,1003317,2053013555631882655,electronics.smartphone,apple,951.99,521082756,4,42,10,1,0,0,1
4,2019-10-21 08:51:20+00:00,1005160,2053013555631882655,electronics.smartphone,xiaomi,224.14,536962600,0,43,10,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10443700,2020-04-16 14:22:36+00:00,11000101,2232732105811427975,appliances.kitchen.grill,philips,46.31,547678064,3,16,4,2,0,0,1
10443701,2020-04-07 18:48:50+00:00,1005004,2232732093077520756,construction.tools.light,huawei,214.65,574177317,1,15,4,2,0,0,1
10443702,2020-04-17 06:46:19+00:00,16200137,2232732108453839552,accessories.bag,pampers,10.98,586450742,4,16,4,2,0,0,1
10443703,2020-04-24 06:17:00+00:00,1306895,2053013554658804075,electronics.audio.headphone,hp,596.93,644915036,4,17,4,2,0,0,1
10443704,2020-04-23 17:45:19+00:00,1005116,2232732093077520756,construction.tools.light,apple,1009.03,640901685,3,17,4,2,1,0,0

In [7]:
df = pd.get_dummies(df, columns=['event_type'], prefix='', prefix_sep='')

In [9]:
df['view'] = df['view'].astype(int)
df['cart'] = df['cart'].astype(int)
df['purchase'] = df['purchase'].astype(int)

In [13]:
df['year'] = df['year'].apply(lambda x: 1 if x == 2019 else 2)

In [17]:
def assign_week_values(week_series):
    unique_weeks = week_series.unique()
    week_map = {week: idx for idx, week in enumerate(sorted(unique_weeks))}
    return week_series.map(week_map)

In [21]:
df_new = df.copy()

In [23]:
df_new['week'] = df_new.groupby('month')['week'].transform(assign_week_values)

In [53]:
sample = df_new.sample(frac= 0.01, random_state=42)

In [55]:
data = sample.to_pickle('muestra.pkl')

In [49]:
df_new.head(-1)

,event_time,product_id,category_id,category_code,brand,price,user_id,day,week,month,year,cart,purchase,view
0,2019-10-21 16:17:11+00:00,1801805,2053013554415534427,electronics.video.tv,artel,231.60,536042235,0,3,10,1,0,0,1
1,2019-10-21 14:42:20+00:00,1004870,2053013555631882655,electronics.smartphone,samsung,284.02,517143806,0,3,10,1,1,0,0
2,2019-10-03 18:40:22+00:00,5701087,2053013553970938175,auto.accessories.player,jvc,51.48,556492770,3,0,10,1,0,0,1
3,2019-10-18 15:55:13+00:00,1003317,2053013555631882655,electronics.smartphone,apple,951.99,521082756,4,2,10,1,0,0,1
4,2019-10-21 08:51:20+00:00,1005160,2053013555631882655,electronics.smartphone,xiaomi,224.14,536962600,0,3,10,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10443700,2020-04-16 14:22:36+00:00,11000101,2232732105811427975,appliances.kitchen.grill,philips,46.31,547678064,3,2,4,2,0,0,1
10443701,2020-04-07 18:48:50+00:00,1005004,2232732093077520756,construction.tools.light,huawei,214.65,574177317,1,1,4,2,0,0,1
10443702,2020-04-17 06:46:19+00:00,16200137,2232732108453839552,accessories.bag,pampers,10.98,586450742,4,2,4,2,0,0,1
10443703,2020-04-24 06:17:00+00:00,1306895,2053013554658804075,electronics.audio.headphone,hp,596.93,644915036,4,3,4,2,0,0,1
10443704,2020-04-23 17:45:19+00:00,1005116,2232732093077520756,construction.tools.light,apple,1009.03,640901685,3,3,4,2,1,0,0

In [29]:
df.category_id.nunique()

1228

In [39]:
data2 = df_new.to_pickle('final.pkl')

In [3]:
dff = pd.read_pickle('final.pkl')

In [5]:
dff.head(-1)

,event_time,product_id,category_id,category_code,brand,price,user_id,day,week,month,year,cart,purchase,view
0,2019-10-21 16:17:11+00:00,1801805,2053013554415534427,electronics.video.tv,artel,231.60,536042235,0,3,10,1,0,0,1
1,2019-10-21 14:42:20+00:00,1004870,2053013555631882655,electronics.smartphone,samsung,284.02,517143806,0,3,10,1,1,0,0
2,2019-10-03 18:40:22+00:00,5701087,2053013553970938175,auto.accessories.player,jvc,51.48,556492770,3,0,10,1,0,0,1
3,2019-10-18 15:55:13+00:00,1003317,2053013555631882655,electronics.smartphone,apple,951.99,521082756,4,2,10,1,0,0,1
4,2019-10-21 08:51:20+00:00,1005160,2053013555631882655,electronics.smartphone,xiaomi,224.14,536962600,0,3,10,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10443700,2020-04-16 14:22:36+00:00,11000101,2232732105811427975,appliances.kitchen.grill,philips,46.31,547678064,3,2,4,2,0,0,1
10443701,2020-04-07 18:48:50+00:00,1005004,2232732093077520756,construction.tools.light,huawei,214.65,574177317,1,1,4,2,0,0,1
10443702,2020-04-17 06:46:19+00:00,16200137,2232732108453839552,accessories.bag,pampers,10.98,586450742,4,2,4,2,0,0,1
10443703,2020-04-24 06:17:00+00:00,1306895,2053013554658804075,electronics.audio.headphone,hp,596.93,644915036,4,3,4,2,0,0,1
10443704,2020-04-23 17:45:19+00:00,1005116,2232732093077520756,construction.tools.light,apple,1009.03,640901685,3,3,4,2,1,0,0

In [9]:
dff['week'].max()

5

In [17]:
data = dff['week']==5

In [27]:
data.nunique()

2

In [45]:
dff.brand.nunique()

5834

In [47]:
dff.user_id.nunique()

8290681

In [ ]:
user_purchase = dff['user_id'].nunique()

In [29]:
df_filtrado = dff[dff['week'] != 5]

In [31]:
df_filtrado.head(-1)

,event_time,product_id,category_id,category_code,brand,price,user_id,day,week,month,year,cart,purchase,view
0,2019-10-21 16:17:11+00:00,1801805,2053013554415534427,electronics.video.tv,artel,231.60,536042235,0,3,10,1,0,0,1
1,2019-10-21 14:42:20+00:00,1004870,2053013555631882655,electronics.smartphone,samsung,284.02,517143806,0,3,10,1,1,0,0
2,2019-10-03 18:40:22+00:00,5701087,2053013553970938175,auto.accessories.player,jvc,51.48,556492770,3,0,10,1,0,0,1
3,2019-10-18 15:55:13+00:00,1003317,2053013555631882655,electronics.smartphone,apple,951.99,521082756,4,2,10,1,0,0,1
4,2019-10-21 08:51:20+00:00,1005160,2053013555631882655,electronics.smartphone,xiaomi,224.14,536962600,0,3,10,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10443700,2020-04-16 14:22:36+00:00,11000101,2232732105811427975,appliances.kitchen.grill,philips,46.31,547678064,3,2,4,2,0,0,1
10443701,2020-04-07 18:48:50+00:00,1005004,2232732093077520756,construction.tools.light,huawei,214.65,574177317,1,1,4,2,0,0,1
10443702,2020-04-17 06:46:19+00:00,16200137,2232732108453839552,accessories.bag,pampers,10.98,586450742,4,2,4,2,0,0,1
10443703,2020-04-24 06:17:00+00:00,1306895,2053013554658804075,electronics.audio.headphone,hp,596.93,644915036,4,3,4,2,0,0,1
10443704,2020-04-23 17:45:19+00:00,1005116,2232732093077520756,construction.tools.light,apple,1009.03,640901685,3,3,4,2,1,0,0

In [33]:
export = df_filtrado.to_pickle('final.pkl')